import { notFound } from 'next/navigation';
import { languages, type Lang } from '../../lib/translations';
import SiteHeader from '../components/SiteHeader';
import { business, mailtoHref } from '../../lib/business';

type Props = { params: Promise<{ lang: string }> };
type Item = { title: string; text: string };
type HomeCopy = {
  heroTitle: string; heroIdentity: string; heroIntro: string; principle: string; sendShort: string; aboutCta: string;
  problemsEyebrow: string; problemsTitle: string; problemsIntro: string; problems: Item[];
  resultsEyebrow: string; resultsTitle: string; resultsIntro: string; resultsSupport: string; results: Item[];
  experienceEyebrow: string; experienceTitle: string; experienceIntro: string; experienceFacts: string[]; independence: string; independenceClosing: string;
  startEyebrow: string; startTitle: string; startIntro: string; steps: Item[];
  tenderEyebrow: string; tenderTitle: string; tenderIntro: string; tenderSupport: string; tenderPrinciple: string; tenderResult: string; tenderCta: string;
  projectsEyebrow: string; projectsTitle: string; projectsIntro: string; project1Title: string; project1Text: string; project2Title: string; project2Text: string; projectsCta: string;
};

const home: Record<Lang, HomeCopy> = {
  en: {
    heroTitle: 'Independent engineering and business consulting for complex decisions', heroIdentity: 'Oleksandr Koretskiy — engineer, independent expert and decision partner.', heroIntro: 'I help clients define the real objective, understand the constraints, compare realistic alternatives and make technical and business decisions that can be implemented and controlled.', principle: 'Finding the essential. Eliminating the unnecessary.', sendShort: 'Send a short description', aboutCta: 'About Oleksandr Koretskiy',
    problemsEyebrow: 'Where I can help', problemsTitle: 'Start with the task, not with the supplier.', problemsIntro: 'Clients usually come to me when the objective is unclear, the constraints conflict, several technical or commercial options need to be compared, or a proposed solution depends too heavily on a supplier or contractor.',
    problems: [{ title: 'Define the real task', text: 'The objective or scope is still unclear.' }, { title: 'Compare alternatives', text: 'Several technologies, configurations or proposals cannot be compared objectively.' }, { title: 'Review a proposed decision', text: 'A technical, commercial or investment decision needs an independent second opinion before commitment.' }, { title: 'Turn an idea into a workable brief', text: 'The intended result is understood, but it still needs to become a clear brief or technical specification.' }],
    resultsEyebrow: 'Consulting result', resultsTitle: 'A decision that is clear enough to execute and control.', resultsIntro: 'The result depends on the task. It may be a defined objective, an independent review, a comparison of alternatives, a clear brief, a technical specification, a decision memo or an implementation roadmap.', resultsSupport: 'The recommendation may confirm the proposed direction, identify a better alternative, simplify the project, postpone a purchase or show that something does not need to be built at all.',
    results: [{ title: 'Clear definition', text: 'The real objective, required result, constraints and unresolved questions.' }, { title: 'Independent comparison', text: 'Realistic alternatives assessed on a consistent technical and business basis.' }, { title: 'Workable documentation', text: 'A brief, technical specification, decision memo or implementation roadmap appropriate to the task.' }, { title: 'Practical recommendation', text: 'A reasoned direction that can be implemented, reviewed and controlled.' }],
    experienceEyebrow: 'Experience and approach', experienceTitle: 'Finding the essential. Eliminating the unnecessary.', experienceIntro: 'My advice is based on more than 35 years of experience in engineering, electromechanics, energy, construction and technical management, including more than 10 years as an independent expert and consultant.', experienceFacts: ['35+ years of professional experience', '10+ years as an independent expert and consultant', 'PhD in Electromechanics', 'Engineering and industrial management background', 'Professional experience across Ukraine, Israel and Serbia'], independence: 'I do not start from a predefined product, supplier or contractor. Equipment, technology, contractors and investment options are considered only after the objective, constraints and realistic alternatives are understood.', independenceClosing: 'If the best answer is to use what already exists, simplify the project, postpone a purchase or not build something at all, that is also a valid consulting result.',
    startEyebrow: 'Start here', startTitle: 'Send a short description of the task.', startIntro: 'You do not need to define the consulting assignment in advance. Send the problem, objective, available proposal, specification or other relevant documents. The first step is to understand what actually needs to be done.', steps: [{ title: '1. Send the task or available documents', text: 'Share a short description and any information already available.' }, { title: '2. Clarify the real decision and required result', text: 'Identify the objective, constraints and questions that need to be answered.' }, { title: '3. Define the scope and deliverable', text: 'Agree whether the task calls for a second opinion, review, comparison, brief, specification, memo or roadmap.' }],
    tenderEyebrow: 'Specialist service', tenderTitle: 'Tender & equipment support', tenderIntro: 'For complex tenders, I analyse the specification, identify mandatory requirements, compare manufacturers and technical equivalents, and help build the technical logic of a workable proposal.', tenderSupport: 'Where one supplier cannot cover the complete scope, the work may include non-standard configurations, compatible multi-supplier packages, specialist input or an appropriate consortium.', tenderPrinciple: 'The tender defines the solution — not the supplier.', tenderResult: 'The result may be a direct match, a technically justified equivalent, a changed configuration or a combined proposal from several companies.', tenderCta: 'Open Tender & Equipment support',
    projectsEyebrow: 'Separately from client consulting', projectsTitle: 'Projects for implementation', projectsIntro: 'I also develop selected technical and business concepts to a stage where practical implementation can be discussed with potential clients, investors, industrial partners, suppliers or operators.', project1Title: 'AI Energy Campus — Serbia', project1Text: 'Modular AI/Data Center infrastructure combining local generation, cooling and energy storage. The current concept starts with a 5 MW pilot and has potential to scale to 50+ MW.', project2Title: 'Integrated climate & energy modernization', project2Text: 'A modular concept for buildings where heating, ventilation, comfort and operating cost need to be addressed as one system.', projectsCta: 'View projects for implementation'
  },
  ru: {
    heroTitle: 'Независимый инженерный и бизнес-консалтинг для сложных решений', heroIdentity: 'Александр Корецкий — инженер, независимый эксперт и партнер по принятию решений.', heroIntro: 'Помогаю определить реальную цель, понять ограничения, сравнить практичные альтернативы и принять технические и бизнес-решения, которые можно реализовать и контролировать.', principle: 'Находить главное. Отсекать лишнее.', sendShort: 'Отправить краткое описание', aboutCta: 'Об Александре Корецком',
    problemsEyebrow: 'Когда я могу помочь', problemsTitle: 'Начинаем с задачи, а не с поставщика.', problemsIntro: 'Обычно ко мне обращаются, когда цель неясна, ограничения противоречат друг другу, нужно объективно сравнить несколько технических или коммерческих вариантов либо предлагаемое решение слишком зависит от конкретного поставщика или подрядчика.',
    problems: [{ title: 'Определить реальную задачу', text: 'Цель или границы проекта пока не ясны.' }, { title: 'Сравнить варианты', text: 'Несколько технологий, конфигураций или предложений невозможно объективно сравнить между собой.' }, { title: 'Проверить предлагаемое решение', text: 'Перед принятием обязательств нужен независимый второй взгляд на техническое, коммерческое или инвестиционное решение.' }, { title: 'Превратить идею в рабочее ТЗ', text: 'Желаемый результат понятен, но его еще нужно оформить в четкий бриф или техническое задание.' }],
    resultsEyebrow: 'Результат консалтинга', resultsTitle: 'Решение, достаточно понятное для реализации и контроля.', resultsIntro: 'Результат зависит от задачи: сформулированная цель, независимая оценка, сравнение альтернатив, рабочий бриф, техническое задание, меморандум по решению или дорожная карта реализации.', resultsSupport: 'Рекомендация может подтвердить выбранное направление, показать лучшую альтернативу, упростить проект, отложить покупку или показать, что что-то вообще не нужно строить.',
    results: [{ title: 'Четкая постановка', text: 'Реальная цель, требуемый результат, ограничения и нерешенные вопросы.' }, { title: 'Независимое сравнение', text: 'Реалистичные альтернативы, оцененные на единой технической и бизнес-основе.' }, { title: 'Рабочие документы', text: 'Бриф, техническое задание, меморандум по решению или дорожная карта под конкретную задачу.' }, { title: 'Практическая рекомендация', text: 'Обоснованное направление, которое можно реализовать, проверить и контролировать.' }],
    experienceEyebrow: 'Опыт и подход', experienceTitle: 'Находить главное. Отсекать лишнее.', experienceIntro: 'В основе моих рекомендаций — более 35 лет опыта в инженерии, электромеханике, энергетике, строительстве и техническом управлении, включая более 10 лет работы независимым экспертом и консультантом.', experienceFacts: ['35+ лет профессионального опыта', '10+ лет как независимый эксперт и консультант', 'PhD по электромеханике', 'Инженерное и управленческое образование', 'Профессиональный опыт в Украине, Израиле и Сербии'], independence: 'Я не начинаю с заранее выбранного продукта, поставщика или подрядчика. Оборудование, технологии, подрядчики и инвестиционные варианты рассматриваются только после того, как понятны цель, ограничения и реальные альтернативы.', independenceClosing: 'Если лучший ответ — использовать то, что уже есть, упростить проект, отложить покупку или вообще ничего не строить, это тоже нормальный результат консалтинга.',
    startEyebrow: 'С чего начать', startTitle: 'Пришлите краткое описание задачи.', startIntro: 'Не нужно заранее формулировать консультационное задание. Пришлите проблему, цель, имеющееся предложение, спецификацию или другие материалы. Первый шаг — понять, что действительно нужно сделать.', steps: [{ title: '1. Пришлите задачу или имеющиеся документы', text: 'Достаточно краткого описания и того, что уже есть.' }, { title: '2. Уточним реальное решение и требуемый результат', text: 'Определим цель, ограничения и вопросы, на которые нужно получить ответ.' }, { title: '3. Определим объем и результат работы', text: 'Согласуем, нужен ли второй взгляд, проверка документов, сравнение, бриф, ТЗ, меморандум или дорожная карта.' }],
    tenderEyebrow: 'Специализированная услуга', tenderTitle: 'Тендеры и оборудование', tenderIntro: 'Для сложных тендеров я анализирую спецификацию, выделяю обязательные требования, сравниваю производителей и технические аналоги и помогаю выстроить техническую логику рабочего предложения.', tenderSupport: 'Если один поставщик не закрывает весь объем, работа может включать нестандартные конфигурации, совместимые решения из оборудования нескольких производителей, профильных специалистов или подходящий консорциум.', tenderPrinciple: 'Решение определяет тендер — не поставщик.', tenderResult: 'Результатом может быть прямое соответствие, технически обоснованный аналог, измененная конфигурация или комбинированное предложение нескольких компаний.', tenderCta: 'Открыть направление «Тендеры и оборудование»',
    projectsEyebrow: 'Отдельно от клиентского консалтинга', projectsTitle: 'Проекты для реализации', projectsIntro: 'Я также разрабатываю отдельные технические и бизнес-концепции до стадии, на которой можно обсуждать практическую реализацию с заказчиками, инвесторами, промышленными партнерами, поставщиками или операторами.', project1Title: 'AI Energy Campus — Serbia', project1Text: 'Модульная инфраструктура AI/Data Center с локальной генерацией, охлаждением и накоплением энергии. Текущая концепция начинается с пилота 5 МВт и предусматривает масштабирование до 50+ МВт.', project2Title: 'Комплексная модернизация микроклимата и энергосистем', project2Text: 'Модульная концепция для зданий, где отопление, вентиляцию, комфорт и эксплуатационные затраты нужно рассматривать как единую систему.', projectsCta: 'Смотреть проекты для реализации'
  },
  uk: {
    heroTitle: 'Незалежний інженерний та бізнес-консалтинг для складних рішень', heroIdentity: 'Олександр Корецький — інженер, незалежний експерт і партнер у прийнятті рішень.', heroIntro: 'Допомагаю визначити реальну мету, зрозуміти обмеження, порівняти практичні альтернативи та прийняти технічні й бізнес-рішення, які можна реалізувати й контролювати.', principle: 'Знаходити головне. Відсікати зайве.', sendShort: 'Надіслати короткий опис', aboutCta: 'Про Олександра Корецького',
    problemsEyebrow: 'Коли я можу допомогти', problemsTitle: 'Починаємо із задачі, а не з постачальника.', problemsIntro: 'Зазвичай до мене звертаються, коли мета неясна, обмеження суперечать одне одному, потрібно об’єктивно порівняти кілька технічних чи комерційних варіантів або запропоноване рішення надто залежить від конкретного постачальника чи підрядника.',
    problems: [{ title: 'Визначити реальну задачу', text: 'Мета або межі проєкту ще не визначені достатньо чітко.' }, { title: 'Порівняти варіанти', text: 'Кілька технологій, конфігурацій або пропозицій неможливо об’єктивно порівняти між собою.' }, { title: 'Перевірити запропоноване рішення', text: 'Перед зобов’язанням потрібна незалежна друга думка щодо технічного, комерційного або інвестиційного рішення.' }, { title: 'Перетворити ідею на робоче ТЗ', text: 'Бажаний результат зрозумілий, але його ще потрібно оформити в чіткий бриф або технічне завдання.' }],
    resultsEyebrow: 'Результат консалтингу', resultsTitle: 'Рішення, достатньо зрозуміле для реалізації та контролю.', resultsIntro: 'Результат залежить від задачі: сформульована мета, незалежний огляд, порівняння альтернатив, робочий бриф, технічне завдання, меморандум щодо рішення або дорожня карта реалізації.', resultsSupport: 'Рекомендація може підтвердити обраний напрям, показати кращу альтернативу, спростити проєкт, відкласти придбання або показати, що щось узагалі не потрібно будувати.',
    results: [{ title: 'Чітка постановка', text: 'Реальна мета, потрібний результат, обмеження та невирішені питання.' }, { title: 'Незалежне порівняння', text: 'Реалістичні альтернативи, оцінені на єдиній технічній та бізнес-основі.' }, { title: 'Робочі документи', text: 'Бриф, технічне завдання, меморандум щодо рішення або дорожня карта відповідно до задачі.' }, { title: 'Практична рекомендація', text: 'Обґрунтований напрям, який можна реалізувати, перевірити й контролювати.' }],
    experienceEyebrow: 'Досвід і підхід', experienceTitle: 'Знаходити головне. Відсікати зайве.', experienceIntro: 'Мої рекомендації спираються на понад 35 років досвіду в інженерії, електромеханіці, енергетиці, будівництві та технічному управлінні, включно з понад 10 роками роботи незалежним експертом і консультантом.', experienceFacts: ['35+ років професійного досвіду', '10+ років як незалежний експерт і консультант', 'PhD з електромеханіки', 'Інженерна та управлінська освіта', 'Професійний досвід в Україні, Ізраїлі та Сербії'], independence: 'Я не починаю із заздалегідь обраного продукту, постачальника чи підрядника. Обладнання, технології, підрядники та інвестиційні варіанти розглядаються лише після того, як зрозумілі мета, обмеження та реальні альтернативи.', independenceClosing: 'Якщо найкраща відповідь — використати те, що вже є, спростити проєкт, відкласти придбання або взагалі нічого не будувати, це також нормальний результат консалтингу.',
    startEyebrow: 'З чого почати', startTitle: 'Надішліть короткий опис задачі.', startIntro: 'Не потрібно заздалегідь формулювати консультаційне завдання. Надішліть проблему, мету, наявну пропозицію, специфікацію чи інші матеріали. Перший крок — зрозуміти, що насправді потрібно зробити.', steps: [{ title: '1. Надішліть задачу або наявні документи', text: 'Достатньо короткого опису та інформації, яка вже є.' }, { title: '2. Уточнимо реальне рішення та потрібний результат', text: 'Визначимо мету, обмеження та питання, на які потрібно відповісти.' }, { title: '3. Визначимо обсяг і результат роботи', text: 'Узгодимо, чи потрібна друга думка, перевірка документів, порівняння, бриф, ТЗ, меморандум або дорожня карта.' }],
    tenderEyebrow: 'Спеціалізована послуга', tenderTitle: 'Тендери та обладнання', tenderIntro: 'Для складних тендерів я аналізую специфікацію, виділяю обов’язкові вимоги, порівнюю виробників і технічні аналоги та допомагаю вибудувати технічну логіку робочої пропозиції.', tenderSupport: 'Якщо один постачальник не покриває весь обсяг, робота може включати нестандартні конфігурації, сумісні рішення з обладнання кількох виробників, профільних спеціалістів або відповідний консорціум.', tenderPrinciple: 'Рішення визначає тендер — не постачальник.', tenderResult: 'Результатом може бути пряме відповідність, технічно обґрунтований аналог, змінена конфігурація або комбінована пропозиція кількох компаній.', tenderCta: 'Відкрити напрям «Тендери та обладнання»',
    projectsEyebrow: 'Окремо від клієнтського консалтингу', projectsTitle: 'Проєкти для реалізації', projectsIntro: 'Я також розробляю окремі технічні та бізнес-концепції до стадії, на якій можна обговорювати практичну реалізацію із замовниками, інвесторами, промисловими партнерами, постачальниками чи операторами.', project1Title: 'AI Energy Campus — Serbia', project1Text: 'Модульна інфраструктура AI/Data Center із локальною генерацією, охолодженням і накопиченням енергії. Поточна концепція починається з пілота 5 МВт і передбачає масштабування до 50+ МВт.', project2Title: 'Комплексна модернізація мікроклімату та енергосистем', project2Text: 'Модульна концепція для будівель, де опалення, вентиляцію, комфорт і експлуатаційні витрати потрібно розглядати як єдину систему.', projectsCta: 'Дивитися проєкти для реалізації'
  },
  sr: {
    heroTitle: 'Nezavisni inženjerski i poslovni konsalting za složene odluke', heroIdentity: 'Oleksandr Koretskiy — inženjer, nezavisni ekspert i partner u donošenju odluka.', heroIntro: 'Pomažem klijentima da definišu stvarni cilj, razumeju ograničenja, uporede realne alternative i donesu tehničke i poslovne odluke koje mogu da se sprovedu i kontrolišu.', principle: 'Pronaći suštinu. Ukloniti suvišno.', sendShort: 'Pošaljite kratak opis', aboutCta: 'O Oleksandru Koretskiyju',
    problemsEyebrow: 'Kada mogu da pomognem', problemsTitle: 'Počinjemo od zadatka, a ne od dobavljača.', problemsIntro: 'Klijenti mi se obično obraćaju kada cilj nije dovoljno jasan, ograničenja su međusobno suprotstavljena, potrebno je objektivno uporediti više tehničkih ili komercijalnih opcija ili predloženo rešenje previše zavisi od određenog dobavljača ili izvođača.',
    problems: [{ title: 'Definisati stvarni zadatak', text: 'Cilj ili obim projekta još nisu dovoljno jasni.' }, { title: 'Uporediti alternative', text: 'Više tehnologija, konfiguracija ili ponuda nije moguće objektivno uporediti.' }, { title: 'Proveriti predloženu odluku', text: 'Pre preuzimanja obaveze potrebna je nezavisna druga procena tehničke, komercijalne ili investicione odluke.' }, { title: 'Pretvoriti ideju u operativni zadatak', text: 'Željeni rezultat je poznat, ali ga još treba pretvoriti u jasan brief ili tehničku specifikaciju.' }],
    resultsEyebrow: 'Rezultat konsaltinga', resultsTitle: 'Odluka dovoljno jasna da može da se sprovede i kontroliše.', resultsIntro: 'Rezultat zavisi od zadatka: definisan cilj, nezavisna procena, poređenje alternativa, jasan brief, tehnička specifikacija, memorandum o odluci ili plan realizacije.', resultsSupport: 'Preporuka može potvrditi predloženi pravac, pokazati bolju alternativu, pojednostaviti projekat, odložiti kupovinu ili pokazati da nešto uopšte ne treba graditi.',
    results: [{ title: 'Jasna definicija', text: 'Stvarni cilj, potreban rezultat, ograničenja i otvorena pitanja.' }, { title: 'Nezavisno poređenje', text: 'Realne alternative procenjene na doslednoj tehničkoj i poslovnoj osnovi.' }, { title: 'Operativna dokumentacija', text: 'Brief, tehnička specifikacija, memorandum o odluci ili plan realizacije prilagođen zadatku.' }, { title: 'Praktična preporuka', text: 'Obrazložen pravac koji može da se sprovede, proveri i kontroliše.' }],
    experienceEyebrow: 'Iskustvo i pristup', experienceTitle: 'Pronaći suštinu. Ukloniti suvišno.', experienceIntro: 'Moje preporuke zasnivaju se na više od 35 godina iskustva u inženjerstvu, elektromehanici, energetici, građevinarstvu i tehničkom upravljanju, uključujući više od 10 godina rada kao nezavisni ekspert i konsultant.', experienceFacts: ['35+ godina profesionalnog iskustva', '10+ godina kao nezavisni ekspert i konsultant', 'PhD iz elektromehanike', 'Inženjersko i industrijsko-menadžersko obrazovanje', 'Profesionalno iskustvo u Ukrajini, Izraelu i Srbiji'], independence: 'Ne polazim od unapred izabranog proizvoda, dobavljača ili izvođača. Oprema, tehnologije, izvođači i investicione opcije razmatraju se tek kada su cilj, ograničenja i realne alternative jasni.', independenceClosing: 'Ako je najbolji odgovor da se iskoristi ono što već postoji, projekat pojednostavi, kupovina odloži ili da se nešto uopšte ne gradi, i to je validan rezultat konsaltinga.',
    startEyebrow: 'Počnite ovde', startTitle: 'Pošaljite kratak opis zadatka.', startIntro: 'Ne morate unapred definisati konsultantski angažman. Pošaljite problem, cilj, postojeću ponudu, specifikaciju ili druge relevantne dokumente. Prvi korak je razumeti šta zaista treba uraditi.', steps: [{ title: '1. Pošaljite zadatak ili dostupnu dokumentaciju', text: 'Dovoljan je kratak opis i informacije koje već imate.' }, { title: '2. Razjasnimo stvarnu odluku i potreban rezultat', text: 'Definišemo cilj, ograničenja i pitanja na koja treba odgovoriti.' }, { title: '3. Definišemo obim i isporuku', text: 'Dogovaramo da li je potreban drugi pogled, pregled dokumenata, poređenje, brief, tehnička specifikacija, memorandum ili plan realizacije.' }],
    tenderEyebrow: 'Specijalistička usluga', tenderTitle: 'Tenderi i oprema', tenderIntro: 'Za složene tendere analiziram specifikaciju, identifikujem obavezne zahteve, upoređujem proizvođače i tehničke ekvivalente i pomažem da se izgradi tehnička logika izvodljive ponude.', tenderSupport: 'Kada jedan dobavljač ne pokriva ceo obim, rad može uključivati nestandardne konfiguracije, kompatibilne pakete više dobavljača, stručnu podršku ili odgovarajući konzorcijum.', tenderPrinciple: 'Tender definiše rešenje — ne dobavljač.', tenderResult: 'Rezultat može biti direktno poklapanje, tehnički opravdan ekvivalent, izmenjena konfiguracija ili kombinovana ponuda više kompanija.', tenderCta: 'Otvori podršku za tendere i opremu',
    projectsEyebrow: 'Odvojeno od konsultinga za klijente', projectsTitle: 'Projekti za realizaciju', projectsIntro: 'Takođe razvijam odabrane tehničke i poslovne koncepte do nivoa na kome se praktična realizacija može razmatrati sa potencijalnim klijentima, investitorima, industrijskim partnerima, dobavljačima ili operaterima.', project1Title: 'AI Energy Campus — Serbia', project1Text: 'Modularna AI/Data Center infrastruktura koja kombinuje lokalnu proizvodnju energije, hlađenje i skladištenje. Trenutni koncept počinje pilotom od 5 MW i može da se skalira na 50+ MW.', project2Title: 'Kompleksna modernizacija mikroklime i energetskih sistema', project2Text: 'Modularni koncept za objekte u kojima grejanje, ventilacija, komfor i operativni troškovi treba da se posmatraju kao jedinstven sistem.', projectsCta: 'Pogledaj projekte za realizaciju'
  }
};

export function generateStaticParams() { return languages.map((lang) => ({ lang })); }

export default async function LocalizedHome({ params }: Props) {
  const { lang: rawLang } = await params;
  if (!languages.includes(rawLang as Lang)) notFound();
  const lang = rawLang as Lang;
  const h = home[lang];
  return <main>
    <SiteHeader lang={lang} languagePath="" />
    <section className="hero" id="top"><p className="eyebrow">{business.operatingName}</p><h1>{h.heroTitle}</h1><p className="lead">{h.heroIdentity}</p><p className="lead-small">{h.heroIntro}</p><p><strong>{h.principle}</strong></p><div className="hero-actions"><a className="button button-dark" href={mailtoHref()}>{h.sendShort}</a><a className="button button-light" href={`/${lang}/about`}>{h.aboutCta}</a></div></section>
    <section className="section" id="services"><div className="section-heading"><p className="eyebrow">{h.problemsEyebrow}</p><h2>{h.problemsTitle}</h2><p className="lead-small">{h.problemsIntro}</p></div><div className="cards home-direction-grid">{h.problems.map((item, index) => <article className="card home-direction-card" key={item.title}><span className="card-number">0{index + 1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">{h.resultsEyebrow}</p><h2>{h.resultsTitle}</h2><p className="lead-small">{h.resultsIntro}</p><p>{h.resultsSupport}</p></div><div className="cards home-direction-grid">{h.results.map((item) => <article className="card home-direction-card" key={item.title}><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>
    <section className="section split" id="approach"><div><p className="eyebrow">{h.experienceEyebrow}</p><h2>{h.experienceTitle}</h2></div><div className="prose"><p>{h.experienceIntro}</p><ul>{h.experienceFacts.map((fact) => <li key={fact}>{fact}</li>)}</ul><p>{h.independence}</p><p>{h.independenceClosing}</p><a className="button button-light" href={`/${lang}/about`}>{h.aboutCta}</a></div></section>
    <section className="section contact"><p className="eyebrow">{h.startEyebrow}</p><h2>{h.startTitle}</h2><p>{h.startIntro}</p><div className="cards home-direction-grid">{h.steps.map((step) => <article className="card home-direction-card" key={step.title}><h3>{step.title}</h3><p>{step.text}</p></article>)}</div><div className="hero-actions"><a className="button button-dark" href={mailtoHref()}>{h.sendShort}</a></div></section>
    <section className="section"><div className="section-heading"><p className="eyebrow">{h.tenderEyebrow}</p><h2>{h.tenderTitle}</h2><p className="lead-small">{h.tenderIntro}</p></div><div className="prose"><p>{h.tenderSupport}</p><p><strong>{h.tenderPrinciple}</strong></p><p>{h.tenderResult}</p><a className="button button-dark" href={`/${lang}/tender-equipment`}>{h.tenderCta}</a></div></section>
    <section className="section" id="current-projects"><div className="section-heading"><p className="eyebrow">{h.projectsEyebrow}</p><h2>{h.projectsTitle}</h2><p className="lead-small">{h.projectsIntro}</p></div><div className="home-project-grid"><article className="home-project-card"><h3>{h.project1Title}</h3><p>{h.project1Text}</p></article><article className="home-project-card"><h3>{h.project2Title}</h3><p>{h.project2Text}</p></article></div><div className="hero-actions"><a className="button button-light" href={`/${lang}/perspectives`}>{h.projectsCta}</a></div></section>
  </main>;
}
